#!/usr/bin/env bash

set -e

# make logs accessible through HTTP
/www/debhelper/prepare/szn-logy

# zmena verze jaffa-skriptu podle verze baliku
ver=$(awk '/szn-picturedetector-web ([^)]*)/ { print substr($2, 2, length($2)-2); exit 0; }' debian/changelog)
sed -i "s/__DEB_VERSION__/$ver/" templ/teng.conf

BACKUP_PWD=$PWD
cd ../..
VERSION=`git log -n 1 --pretty="format:%h" 2> /dev/null` ||
  VERSION=`svnversion | sed 's/[^0-9]*\([0-9]\+\).*/\1/'`
cd "$BACKUP_PWD"
CONF_FILE="conf/web.conf"
sed -i "s/{AUTO_FILL_VERSION}/$VERSION/g" $CONF_FILE

